#!/usr/bin/env python
import cv2
import tensorflow as tf
import numpy as np
from PIL import Image
cv2.namedWindow("object detection")
CATEGORIES = ["dog","cat"]
model = tf.keras.models.load_model("md.h5")
cap = cv2.VideoCapture(0)
ret,image=cap.read()
while ret:
    cv2.imshow('object detection', image)
    ret,image=cap.read()
    im = np.resize(image,(32,32,3))
    image_np_expanded = np.expand_dims(im, axis=0)
    prediction = model.predict([image_np_expanded])
    print(prediction)
    print(CATEGORIES[int(prediction[0][0])])
    key = cv2.waitKey(20)
    if key == 27:
           cv2.destroyAllWindows()
           break
